const pages=[['index.html','Home'],['about.html','About'],['skills.html','Skills'],['projects.html','Projects'],['experience.html','Experience'],['certificates.html','Credentials'],['gallery.html','Gallery'],['cv.html','CV'],['contact.html','Contact']];
const current=document.body.dataset.page||location.pathname.split('/').pop()||'index.html';
const nav=pages.map(([href,label])=>`<a href="${href}" class="${current===href?'active':''}">${label}</a>`).join('');
document.getElementById('site-header').innerHTML=`<header class="site-header"><a class="brand" href="index.html"><span class="brand-mark">FM</span><span>Fredrick Muema Musyoki<small>ICT • AI • Builder</small></span></a><nav class="nav" aria-label="Primary">${nav}</nav><button class="header-cta desktop-command" data-command>COMMAND ⌘K</button><button class="mobile-menu-toggle" type="button" aria-label="Open navigation" aria-expanded="false" aria-controls="mobile-sidebar"><span></span><span></span><span></span></button></header>`;
document.getElementById('site-footer').innerHTML=`<footer class="exclusive-footer"><div class="container footer-main"><div><div class="footer-brand">Fredrick Muema Musyoki.</div><p class="footer-lead">A portfolio built around a simple idea: real context, real progress, and an interface that feels alive. Technology is the craft; curiosity is the engine.</p><a class="btn btn-cyan" href="contact.html">Start a conversation ↗</a></div><div><div class="footer-title">Explore</div><div class="footer-links">${pages.slice(0,6).map(p=>`<a href="${p[0]}">${p[1]}</a>`).join('')}</div></div><div><div class="footer-title">Connect</div><div class="footer-links"><a href="mailto:fredrickmuema56@gmail.com">Email me</a><a href="tel:+254768671135">Call +254 768 671 135</a><a href="cv.html">View CV</a><a href="gallery.html">Photo archive</a></div></div><div class="footer-orbit"><div class="planet"></div></div></div><div class="container footer-bottom"><span><strong>FM / 2026</strong> • Nairobi, Kenya • Built to keep evolving.</span><span>SCI — Strategic Cognitive Intelligence • Flagship exploration</span></div></footer>`;
const command=`<div class="command" id="command"><div class="command-box"><input id="commandInput" placeholder="Jump to a page…" aria-label="Command search"><div class="command-list">${pages.map(p=>`<a href="${p[0]}" data-command-link>${p[1]}</a>`).join('')}</div></div></div>`;
const mobileSidebar=`<aside class="mobile-sidebar" id="mobile-sidebar" aria-label="Mobile navigation" aria-hidden="true"><div class="mobile-sidebar-head"><strong>Navigate</strong><button class="mobile-sidebar-close" type="button" aria-label="Close navigation">×</button></div><nav>${pages.map(p=>`<a href="${p[0]}" class="${current===p[0]?'active':''}">${p[1]}<span>↗</span></a>`).join('')}</nav></aside><div class="mobile-sidebar-backdrop" data-mobile-close></div>`;document.body.insertAdjacentHTML('beforeend',command+mobileSidebar);
const modal=document.getElementById('command'),input=document.getElementById('commandInput');
function openCommand(){modal.classList.add('open');setTimeout(()=>input.focus(),30)}function closeCommand(){modal.classList.remove('open')}
document.querySelectorAll('[data-command]').forEach(b=>b.addEventListener('click',openCommand));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand()}if(e.key==='Escape'){closeCommand();closeMobileSidebar()}});modal.addEventListener('click',e=>{if(e.target===modal)closeCommand()});input.addEventListener('input',()=>{const q=input.value.toLowerCase();document.querySelectorAll('[data-command-link]').forEach(a=>a.style.display=a.textContent.toLowerCase().includes(q)?'block':'none')});
const menuToggle=document.querySelector('.mobile-menu-toggle'),mobileSidebarEl=document.getElementById('mobile-sidebar');
function openMobileSidebar(){mobileSidebarEl.classList.add('open');mobileSidebarEl.setAttribute('aria-hidden','false');menuToggle.setAttribute('aria-expanded','true');document.body.classList.add('mobile-menu-open')}function closeMobileSidebar(){if(!mobileSidebarEl)return;mobileSidebarEl.classList.remove('open');mobileSidebarEl.setAttribute('aria-hidden','true');menuToggle?.setAttribute('aria-expanded','false');document.body.classList.remove('mobile-menu-open')}
menuToggle?.addEventListener('click',()=>mobileSidebarEl.classList.contains('open')?closeMobileSidebar():openMobileSidebar());document.querySelector('.mobile-sidebar-close')?.addEventListener('click',closeMobileSidebar);document.querySelector('[data-mobile-close]')?.addEventListener('click',closeMobileSidebar);mobileSidebarEl?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMobileSidebar));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const line=document.createElement('div');line.className='scroll-line';document.body.appendChild(line);addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;line.style.width=(h>0?scrollY/h*100:0)+'%'},{passive:true});
const stage=document.querySelector('.portrait-wrap');if(stage){addEventListener('pointermove',e=>{const x=(e.clientX/innerWidth-.5)*10,y=(e.clientY/innerHeight-.5)*-8;stage.style.transform=`rotateY(${x}deg) rotateX(${y}deg)`});}
const lightbox=document.createElement('div');lightbox.className='lightbox';lightbox.innerHTML='<button class="lightbox-close" aria-label="Close">×</button><img alt="">';document.body.appendChild(lightbox);const lbImg=lightbox.querySelector('img');document.querySelectorAll('[data-lightbox]').forEach(el=>{const openLightbox=(e)=>{if(e){e.preventDefault();e.stopPropagation()}lbImg.src=el.dataset.lightbox;lbImg.alt=el.dataset.title||'';lightbox.classList.add('open')};el.addEventListener('click',openLightbox);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){openLightbox(e)}})});lightbox.addEventListener('click',e=>{if(e.target===lightbox||e.target.classList.contains('lightbox-close'))lightbox.classList.remove('open')});
